### ISSUE TITLE
app-misc/fzf - completion.bash installed into wrong directory

### ISSUE THREAD

**Issue by gene-pavlovsky** [andjscott/overlays#1]
https://github.com/andjscott/overlays/blob/master/app-misc/fzf/fzf-0.12.0.ebuild#L24
The file `completion.bash` should not be installed into `/usr/share/bash-completion/completions`, but rather to `/etc/bash_completion.d`. 
The first dir holds completions that are loaded on-demand for particular commands. Installing `completion.bash` there as `fzf` will source the file only when the user types `fzf` and press tab twice. But `completion.bash` doesn't contain completions for the command `fzf`, it contents completions that add ability to use `**` to various standard commands (e.g. `cp`, `cd`, `unset` etc.). So this file should be sourced when bash_completion is initialized - means it should be in `/etc/bash_completion.d`.

On a side note, it would be nicer if the downloaded distfile was saved as `fzf-0.12.0.tar.gz`, not `0.12.0.tar.gz`, is that possible with ebuilds?

**Comment by ayyess** [comment]
And good note about the naming of files. I've updated fzf's ebuild to rename the tar file.

**Comment by gene-pavlovsky** [comment]
Great, thanks!
