### ISSUE TITLE
Use the newer `Go` version instead of the old `ruby` script

### ISSUE THREAD

**Issue by gene-pavlovsky** [andjscott/overlays#2]
If you `less` the `fzf` file, there is a note: _This script is no longer maintained. Use the new Go version._
The ebuild currently installs the old `ruby` script. The new `Go` version is in `src/`. I don't know anything about `Go`, so I'm not even sure how to compile it (have to play with it more). If you can do it, would be nice. The `ruby` dependency can be dropped then. Maybe it would make sense to split the build in two - one depending on `ruby` and offering the old script (for people who are really bothered to install `Go`), another depending on `Go` and offering just the new version. The newer `fzf` features are only available in the `Go` version.
Side note, the `install.sh` script have an option to download a pre-compiled binary (but I guess it's not the Gentoo way, is it? Unless it's a binary package ebuild).

**Comment by gene-pavlovsky** [comment]
**junegunn**:

> The Makefile is for building both 32-bit and 64-bit binaries on 64-bit machine. I use it to build official binaries, but you don't have to use it. The easiest way to build fzf on your system is to set up Go development environment (i.e. $GOPATH) and go get github.com/junegunn/fzf/src/fzf and it will put the built binary in $GOPATH/bin.

I was able to build it (both 32-bit and 64-bit versions) from source by removing these lines from `src/Makefile`:

```
ifneq ($(shell uname -m),x86_64)
$(error "Build on $(UNAME_M) is not supported, yet.")
endif
```

I've never written any ebuilds, though, so I have no idea what to do next :)

**Comment by ayyess** [comment]
> Maybe it would make sense to split the build in two - one depending on ruby and offering the old script (for people who are really bothered to install Go), another depending on Go and offering just the new version. 

I think a USE flag would be good here - by default it should compile the go code but if go is disabled, install the ruby version.

> the install.sh script have an option to download a pre-compiled binary (but I guess it's not the Gentoo way, is it? Unless it's a binary package ebuild).

Generally no, but some of the larger packages have binary packages (eclipse-sdk-bin, thunderbird-bin, firefox-bin, etc,

**Comment by ayyess** [comment]
> I was able to build it (both 32-bit and 64-bit versions) 

That error should only occur when on a 32-bit machine. Are you on one?
In the Makefile, it looks like `fzf/$(BINARY64)` is a native build rather than specifically 64-bit. If you are 32-bit, could you check this by running `file` on the two executables. 

If this is the case, the ebuild should just build `fzf/$(BINARY64)` rather than trying to build the two versions and a patch can be written to remove the error message.

**Comment by gene-pavlovsky** [comment]
Wow you were real quick in implementing this, thanks!
Now the ebuild goes until the compile phase, then barfs with the expected

```
make -j2 install
Makefile:11: *** "Build on  is not supported, yet.".  Stop.
 * ERROR: app-misc/fzf-0.12.0-r2::andjscott failed (compile phase):
 *   emake failed
```

Frankly, I'm not sure about my machine. It's a remote VPS (by RapidVPS), running on OpenVZ, as far as I know.
`uname -m` returns `i686`, but from `/proc/cpuinfo`: `model name      : Intel(R) Xeon(R) CPU           E5530  @ 2.40GHz`

I googled `Xeon E5530` and it's a 64-bit CPU. But maybe that is IA64, not x86-64? Either way, when I build the source manually, both executables have identical description and look like 32-bit:

```
fzf-linux_386:   ELF 32-bit LSB executable, Intel 80386, ...
fzf-linux_amd64: ELF 32-bit LSB executable, Intel 80386, ...
```

Both of them run fine. Btw in my case each file is a whopping 3.1 Mb, `strip`-ping them reduces size to 2.1 Mb - still big, but better. Does it make sense to `strip` in an ebuild?

**Comment by ayyess** [comment]
I've updated the ebuild to compile without the makefile. Could you try it out? 
I don't know much about Go but it does seem to have a problem with large files.

**Comment by gene-pavlovsky** [comment]
Thanks. There was an error-like message in the middle of compiling, is that normal? The ebuild continued and installed after that. I don't know about Go either.

```
>>> Compiling source in /var/tmp/portage/app-misc/fzf-0.12.1-r1/work/fzf-0.12.1 ...
go install: no install location for directory /var/tmp/portage/app-misc/fzf-0.12.1-r1/work/fzf-0.12.1/src outside GOPATH
        For more details see: go help gopath
>>> Source compiled.
```

**Comment by ayyess** [comment]
I couldn't find out exactly what that error message is about. The ebuild now uses fzf's Makefile with a patch to remove the uname -m error. Hopefully it will work on a 32 bit machine fine.

**Comment by gene-pavlovsky** [comment]
Works with no errors or warnings now. Great job, thanks!
Btw, in gentoo, how is it decided whether an ebuild goes into the official gentoo repository, and what does not? Looks like fzf is quite widely used tool, it's not a niche thing, it would make sense if your ebuild was included in the mainline (or what's the proper word).

**Comment by ayyess** [comment]
Fantastic! I think ebuilds first go through the [sunrise](https://wiki.gentoo.org/wiki/Project:Sunrise) overlay. I may look into merging this repo into sunrise.

**Comment by gene-pavlovsky** [comment]
I see, hopefully it'll get into portage soon. Wish more people can enjoy fzf :)
Thanks !
