### ISSUE TITLE
app-laptop/mbpfan: maintainership inquiry

### ISSUE THREAD

**Issue by gktrk** [andjscott/overlays#3]
Hi,

I've added this package to the official Gentoo repository: https://packages.gentoo.org/packages/app-laptop/mbpfan

Would you like to be listed as the primary or secondary maintainer for it?

**Comment by ayyess** [comment]
I am no longer running a mac (or gentoo for that matter) so won't be able to maintain this ebuild so you'll have to only list your name. Nice job on getting it in the official repository!
